// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace PersonalFinance.Data.Migrations
{
    public partial class RemoveCategoryType : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // TODO: Change category of (recurring) transactions to expense counterpart if possible
            // TODO: Delete income categories if expense counterpart exists
            
            migrationBuilder.DropColumn(
                name: "Type",
                table: "Categories");
            
            // Set Income transactions to External
            migrationBuilder.Sql("UPDATE [dbo].[Transactions] SET [Type] = 1 WHERE [Type] = 2;");
            // Set Transfer transactions to Internal
            migrationBuilder.Sql("UPDATE [dbo].[Transactions] SET [Type] = 2 WHERE [Type] = 3;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "Type",
                table: "Categories",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}
