// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace PersonalFinance.Data.Migrations
{
    public partial class ComputedCurrentBalanceColumn : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE FUNCTION [dbo].GetCurrentBalance(@accountId INT)
                RETURNS DECIMAL(12,2) WITH SCHEMABINDING
                BEGIN
                    DECLARE @ret DECIMAL(12,2);

                    -- Get latest account balance.
                    SELECT TOP 1 @ret = [Balance]
                    FROM [dbo].[DailyBalances]
                    WHERE AccountId = @accountId
                    ORDER BY Date DESC;

                    -- Default to 0 if nothing found.
                    IF (@ret IS NULL)
                        SET @ret = 0;
                    
                    RETURN @ret;
                END");

            migrationBuilder.AddColumn<decimal>(
                name: "CurrentBalance",
                table: "Accounts",
                type: "decimal(12,2)",
                nullable: false,
                computedColumnSql: "[dbo].GetCurrentBalance([Id])");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CurrentBalance",
                table: "Accounts");
        }
    }
}
