// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace PersonalFinance.Data.Migrations
{
    public partial class SplitDetailOnSplitwiseTransaction : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SplitDetails_BaseTransactions_TransactionId",
                table: "SplitDetails");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SplitDetails",
                table: "SplitDetails");

            migrationBuilder.AlterColumn<int>(
                name: "TransactionId",
                table: "SplitDetails",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "SplitDetails",
                type: "int",
                nullable: false,
                defaultValue: 0)
                .Annotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddColumn<int>(
                name: "SplitwiseTransactionId",
                table: "SplitDetails",
                type: "int",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_SplitDetails",
                table: "SplitDetails",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_SplitDetails_SplitwiseTransactionId_SplitwiseUserId",
                table: "SplitDetails",
                columns: new[] { "SplitwiseTransactionId", "SplitwiseUserId" },
                unique: true,
                filter: "[SplitwiseTransactionId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_SplitDetails_TransactionId_SplitwiseUserId",
                table: "SplitDetails",
                columns: new[] { "TransactionId", "SplitwiseUserId" },
                unique: true,
                filter: "[TransactionId] IS NOT NULL");

            migrationBuilder.AddForeignKey(
                name: "FK_SplitDetails_BaseTransactions_TransactionId",
                table: "SplitDetails",
                column: "TransactionId",
                principalTable: "BaseTransactions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_SplitDetails_SplitwiseTransactions_SplitwiseTransactionId",
                table: "SplitDetails",
                column: "SplitwiseTransactionId",
                principalTable: "SplitwiseTransactions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SplitDetails_BaseTransactions_TransactionId",
                table: "SplitDetails");

            migrationBuilder.DropForeignKey(
                name: "FK_SplitDetails_SplitwiseTransactions_SplitwiseTransactionId",
                table: "SplitDetails");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SplitDetails",
                table: "SplitDetails");

            migrationBuilder.DropIndex(
                name: "IX_SplitDetails_SplitwiseTransactionId_SplitwiseUserId",
                table: "SplitDetails");

            migrationBuilder.DropIndex(
                name: "IX_SplitDetails_TransactionId_SplitwiseUserId",
                table: "SplitDetails");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "SplitDetails");

            migrationBuilder.DropColumn(
                name: "SplitwiseTransactionId",
                table: "SplitDetails");

            migrationBuilder.AlterColumn<int>(
                name: "TransactionId",
                table: "SplitDetails",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_SplitDetails",
                table: "SplitDetails",
                columns: new[] { "TransactionId", "SplitwiseUserId" });

            migrationBuilder.AddForeignKey(
                name: "FK_SplitDetails_BaseTransactions_TransactionId",
                table: "SplitDetails",
                column: "TransactionId",
                principalTable: "BaseTransactions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
