// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace PersonalFinance.Data.Migrations
{
    public partial class SplitwiseIdSize : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Transactions_SplitwiseTransactions_SplitwiseTransactionId",
                table: "Transactions");

            migrationBuilder.DropForeignKey(
                name: "FK_SplitDetails_SplitwiseTransactions_SplitwiseTransactionId",
                table: "SplitDetails");
            
            migrationBuilder.AlterColumn<long>(
                name: "SplitwiseTransactionId",
                table: "Transactions",
                type: "bigint",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.DropPrimaryKey(
                name: "PK_SplitwiseTransactions",
                table: "SplitwiseTransactions");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "SplitwiseTransactions",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SplitwiseTransactions",
                table: "SplitwiseTransactions",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Transactions_SplitwiseTransactions_SplitwiseTransactionId",
                table: "Transactions",
                column: "SplitwiseTransactionId",
                principalTable: "SplitwiseTransactions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AlterColumn<long>(
                name: "SplitwiseUserId",
                table: "SplitDetails",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AlterColumn<long>(
                name: "SplitwiseTransactionId",
                table: "SplitDetails",
                type: "bigint",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_SplitDetails_SplitwiseTransactions_SplitwiseTransactionId",
                table: "SplitDetails",
                column: "SplitwiseTransactionId",
                principalTable: "SplitwiseTransactions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "SplitwiseTransactionId",
                table: "Transactions",
                type: "int",
                nullable: true,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "SplitwiseTransactions",
                type: "int",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint");

            migrationBuilder.AlterColumn<int>(
                name: "SplitwiseUserId",
                table: "SplitDetails",
                type: "int",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint");

            migrationBuilder.AlterColumn<int>(
                name: "SplitwiseTransactionId",
                table: "SplitDetails",
                type: "int",
                nullable: true,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldNullable: true);
        }
    }
}
