name: Build - Test - Deploy

on:
  push:
    branches:
      - master

jobs:
  buildTestAndDeploy:
    runs-on: ubuntu-latest
    env:
      workingDirectory: ./Wv8.Finance.Back-End
      dataExternalIntegrationTestDirectory: ./Wv8.Finance.Back-End/Data.External.IntegrationTest
      appSettingsDirectory: ./Wv8.Finance.Back-End/Service
      AZURE_WEBAPP_NAME: wv8-finance
      AZURE_WEBAPP_PACKAGE_PATH: "./Wv8.Finance.Back-End"
      DOTNET_VERSION: "5.0.102"
      packageSourceUrl: https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/nuget/v3/index.json
    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: localDatabase1
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          source-url: ${{env.packageSourceUrl}}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}}
      - name: Build with dotnet
        run: dotnet build --configuration Release /warnaserror
        working-directory: ${{env.workingDirectory}}
      - name: Set Splitwise test API key
        run: sed -i 's@{secrets.SplitwiseTestApiKey}@${{secrets.SPLITWISE_TEST_API_KEY}}@g' appsettings.test.json
        working-directory: ${{env.dataExternalIntegrationTestDirectory}}
      - name: Test
        run: dotnet test
        working-directory: ${{env.workingDirectory}}
      - name: Set Splitwise production API key
        run: sed -i 's@{secrets.SplitwiseApiKey}@${{secrets.SPLITWISE_API_KEY}}@g' appsettings.Production.json
        working-directory: ${{env.appSettingsDirectory}}
      - name: Set Splitwise production user id
        run: sed -i 's@{secrets.SplitwiseUserId}@${{secrets.SPLITWISE_USER_ID}}@g' appsettings.Production.json
        working-directory: ${{env.appSettingsDirectory}}
      - name: Set Splitwise production group id
        run: sed -i 's@{secrets.SplitwiseGroupId}@${{secrets.SPLITWISE_GROUP_ID}}@g' appsettings.Production.json
        working-directory: ${{env.appSettingsDirectory}}
      - name: Publish with dotnet
        run: dotnet publish Service -c Release -o publish
        working-directory: ${{env.workingDirectory}}
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE  }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish"
