name: .NET Core

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workingDirectory: ./Wv8.Finance.Back-End
      AZURE_WEBAPP_NAME: wv8-finance
      AZURE_WEBAPP_PACKAGE_PATH: './Wv8.Finance.Back-End'
      DOTNET_VERSION: '3.1.100'
      packageSourceUrl: https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/nuget/v3/index.json

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
        source-url: ${{env.packageSourceUrl}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{env.workingDirectory}}
    - name: Test
      run: dotnet test
      working-directory: ${{env.workingDirectory}}
    # Run dotnet build and publish
    - name: Publish with dotnet
      run: dotnet publish -c Release -o myapp
      working-directory: ${{env.workingDirectory}}
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
