name: .NET Core

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workingDirectory: ./Wv8.Finance.Back-End

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100
      env:
        NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{env.workingDirectory}}
    - name: Test
      run: dotnet test
      working-directory: ${{env.workingDirectory}}
