name: Pull Request - Build and Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workingDirectory: ./Wv8.Finance.Back-End

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100
        source-url: https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}}
    - name: Build with dotnet
      run: dotnet build --configuration Release /warnaserror
      working-directory: ${{env.workingDirectory}}
    - name: Test
      run: dotnet test
      working-directory: ${{env.workingDirectory}}
